### ISSUE TITLE
MCM not displaying/working properly.

### ISSUE THREAD

**Issue by naturalinhuman** [Neanka/MCM_0.1_AS3#14] opened 2017-12-20 05:13 UTC
MCM will appear in the pause menu, but always at the 6th spot and when I open it I can't change any of its own settings (pic 2 & 3). 

2
![20171219220244_1](https://user-images.githubusercontent.com/34701217/34192344-af6d878c-e50a-11e7-8381-b4ef7f3242d2.jpg)

3
![20171219220253_1](https://user-images.githubusercontent.com/34701217/34192349-b4ffd8ee-e50a-11e7-93af-75c4169ebaad.jpg)

I load all my mods on Mod Organizer (MO)(pic 1). I have tried starting a new game with no other mods other than MCM and F4SE (latest v0.6.4) and its own demo (v1.11).  When I tried installing it manually none of the options would appear in its own menu. Since the MO installation is working slightly better, I'll stick with that installation method. 

1
![pic 1](https://user-images.githubusercontent.com/34701217/34192167-9cc99e82-e509-11e7-8486-dfebf9f0d9d5.PNG)

However, other mods that have MCM addons (extended dialogue interface, HoloTime, (MCM not required)) will not load properly on their own either so I suspect I have a different/another problem. I just wanted to make sure that there is nothing I can do about this mod before trying to fix the other issues.

**Comment by Neanka** [comment] 2017-12-20 17:13
I can't help with MO2 :]

**Comment by reg2k** [comment] 2018-02-25 14:36
The current MO2 maintainer has mentioned that the latest release should fix compatibility with MCM-enabled mods and require no additional configuration for MCM to work. Please try updating your MO2 release.

Closing as this is not a bug in MCM.

**Closed by reg2k** 2018-02-25 14:36 UTC
